spring:
  application:
    name: demo
  datasource:
    url: ${DB1_URL}
    username: ${DB1_USERNAME}
    password: ${DB1_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update   # 可选值: none | update | create | create-drop
    show-sql: true       # 控制台显示 SQL 语句
    properties:
      hibernate:
        format_sql: true # 格式化输出 SQL

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE